# Generated by Django 3.2.9 on 2021-11-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
