# Generated by Django 3.2.9 on 2021-12-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20211130_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='population',
        ),
        migrations.AlterField(
            model_name='data',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес Банкомата'),
        ),
        migrations.AlterField(
            model_name='data',
            name='latitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='longitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
