# Generated by Django 3.2.8 on 2022-02-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20211203_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='filled',
            field=models.BooleanField(default=False),
        ),
    ]
