# Generated by Django 3.2.8 on 2022-02-09 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_data_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='balance',
        ),
    ]
