# Generated by Django 3.2.8 on 2022-02-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_data_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='balance',
            field=models.IntegerField(default=10000),
        ),
    ]
